services:
  job-finder-agent:
    image: job-finder-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-finder-agent
    command: ["reflex", "run", "--env", "prod"]
    network_mode: host
    environment:
      - ENV=prod
      - MOUNT_FOLDER=/mnt
    volumes:
      - ./data:/mnt
    env_file:
      - .env
    restart: unless-stopped

  job-finder-agent-mcp:
    image: job-finder-agent:latest
    container_name: job-finder-agent-mcp
    command: ["python", "mcp_server.py"]
    network_mode: host
    environment:
      - ENV=prod
      - MOUNT_FOLDER=/mnt
    volumes:
      - ./data:/mnt
    env_file:
      - .env
    restart: unless-stopped
